[tool.poetry]
name = "scouts_kampvisum_api"
version = "0.1.0"
description = "An app for entering scout camp data"
authors = ["Inuits"]
license = "GPL v2.0"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.6"
mozilla-django-oidc = "^2.0.0"
drf-yasg2 = "^1.19.4"
cffi = "^1.14.6"
django-cors-headers = "^3.7.0"
django-rest-framework = "^0.1.0"
django-sql-middleware = "^0.0.7"
django-storages = "^1.11.1"
environs = "^9.3.2"
future = "^0.18.2"
psycopg2-binary = "^2.9.1"
scouts-auth = {path = "scouts-auth-0.1.tar.gz"}
django-filter = "^2.4.0"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
