# Generated by Django 4.2.20 on 2026-02-27 09:04

from django.db import migrations, models
import django.db.models.deletion
import scouts_auth.inuits.models.fields.django_shorthand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedSelectCheck',
            fields=[
                ('linkedcheck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visums.linkedcheck')),
                ('value', scouts_auth.inuits.models.fields.django_shorthand_model_fields.OptionalCharField(blank=True, default='', max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=('visums.linkedcheck',),
        ),
    ]
